default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres #default if not created
  password: password
  pool: 5

development:
  <<: *default
  database: ping_pong_development

test:
  <<: *default
  database: ping_pong_test

production:
  <<: *default
  database: ping_pong_production
  username: postgres
  password: <%= ENV['PING_PONG_DATABASE_PASSWORD'] %>

# Vagrant configuration
# default: &default
#   adapter: postgresql
#   encoding: unicode
#   username: vagrant
#   # host: localhost
#   pool: 5
#
# development:
#   <<: *default
#   database: ping_pong_development
#
# test:
#   <<: *default
#   database: ping_pong_test
#
# production:
#   <<: *default
#   database: ping_pong_production
#   password: <%= ENV['ping_pong_DATABASE_PASSWORD'] %>
